name: unix_domain_socket
version: 0.0.0-dev.2
description: Native bindings for Unix domain sockets.
homepage: https://github.com/CanonicalLtd/unix_domain_socket.dart

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  ffi: ^0.1.3
